name: CI  
  
on:  
  push:  
    branches:  
      - 'v2.4.x'  
  pull_request:  
    branches:  
      - 'v2.4.x'
  watch:
    types: started
  
jobs:  
  build-and-test:  
    name: Build and Test  
    strategy:  
      matrix:  
        go-version: [1.18, 1.19, 1.20, 1.21, 1.22]  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  
  
      - name: Setup Go  
        uses: actions/setup-go@v3  
        with:  
          go-version: ${{ matrix.go-version }}  
  
      - name: Get dependencies  
        run: go mod tidy  
  
      - name: Build  
        run: go build -v ./...  
  
      - name: Run tests  
        run: go test -v -tags unit ./...  
  
      - name: Check code coverage (optional)  
        if: matrix.go-version == '1.22' # Optionally, only check coverage on the latest Go version  
        run: go test -v -tags unit ./...  -coverprofile=coverage.txt && go tool cover -html=coverage.txt -o coverage.html  
  
      - name: Upload coverage report (optional)  
        if: matrix.go-version == '1.22'  
        uses: codecov/codecov-action@v2  
        with:  
          file: ./coverage.txt
